// Transcription languages supported by Whisper. Codes mirror the backend set
// (faster-whisper's _LANGUAGE_CODES, exposed via backend app/core/languages.py);
// keep both in sync. Names are French, for the UI. "auto" is not in this list —
// it's handled separately by the selector as the default option.
export const LANGUAGES = [
  { code: "af", name: "Afrikaans" },
  { code: "am", name: "Amharique" },
  { code: "ar", name: "Arabe" },
  { code: "as", name: "Assamais" },
  { code: "az", name: "Azéri" },
  { code: "ba", name: "Bachkir" },
  { code: "be", name: "Biélorusse" },
  { code: "bg", name: "Bulgare" },
  { code: "bn", name: "Bengali" },
  { code: "bo", name: "Tibétain" },
  { code: "br", name: "Breton" },
  { code: "bs", name: "Bosnien" },
  { code: "ca", name: "Catalan" },
  { code: "cs", name: "Tchèque" },
  { code: "cy", name: "Gallois" },
  { code: "da", name: "Danois" },
  { code: "de", name: "Allemand" },
  { code: "el", name: "Grec" },
  { code: "en", name: "Anglais" },
  { code: "es", name: "Espagnol" },
  { code: "et", name: "Estonien" },
  { code: "eu", name: "Basque" },
  { code: "fa", name: "Persan" },
  { code: "fi", name: "Finnois" },
  { code: "fo", name: "Féroïen" },
  { code: "fr", name: "Français" },
  { code: "gl", name: "Galicien" },
  { code: "gu", name: "Goudjarati" },
  { code: "ha", name: "Haoussa" },
  { code: "haw", name: "Hawaïen" },
  { code: "he", name: "Hébreu" },
  { code: "hi", name: "Hindi" },
  { code: "hr", name: "Croate" },
  { code: "ht", name: "Créole haïtien" },
  { code: "hu", name: "Hongrois" },
  { code: "hy", name: "Arménien" },
  { code: "id", name: "Indonésien" },
  { code: "is", name: "Islandais" },
  { code: "it", name: "Italien" },
  { code: "ja", name: "Japonais" },
  { code: "jw", name: "Javanais" },
  { code: "ka", name: "Géorgien" },
  { code: "kk", name: "Kazakh" },
  { code: "km", name: "Khmer" },
  { code: "kn", name: "Kannada" },
  { code: "ko", name: "Coréen" },
  { code: "la", name: "Latin" },
  { code: "lb", name: "Luxembourgeois" },
  { code: "ln", name: "Lingala" },
  { code: "lo", name: "Laotien" },
  { code: "lt", name: "Lituanien" },
  { code: "lv", name: "Letton" },
  { code: "mg", name: "Malgache" },
  { code: "mi", name: "Maori" },
  { code: "mk", name: "Macédonien" },
  { code: "ml", name: "Malayalam" },
  { code: "mn", name: "Mongol" },
  { code: "mr", name: "Marathi" },
  { code: "ms", name: "Malais" },
  { code: "mt", name: "Maltais" },
  { code: "my", name: "Birman" },
  { code: "ne", name: "Népalais" },
  { code: "nl", name: "Néerlandais" },
  { code: "nn", name: "Norvégien (nynorsk)" },
  { code: "no", name: "Norvégien" },
  { code: "oc", name: "Occitan" },
  { code: "pa", name: "Pendjabi" },
  { code: "pl", name: "Polonais" },
  { code: "ps", name: "Pachto" },
  { code: "pt", name: "Portugais" },
  { code: "ro", name: "Roumain" },
  { code: "ru", name: "Russe" },
  { code: "sa", name: "Sanskrit" },
  { code: "sd", name: "Sindhi" },
  { code: "si", name: "Cingalais" },
  { code: "sk", name: "Slovaque" },
  { code: "sl", name: "Slovène" },
  { code: "sn", name: "Shona" },
  { code: "so", name: "Somali" },
  { code: "sq", name: "Albanais" },
  { code: "sr", name: "Serbe" },
  { code: "su", name: "Soundanais" },
  { code: "sv", name: "Suédois" },
  { code: "sw", name: "Swahili" },
  { code: "ta", name: "Tamoul" },
  { code: "te", name: "Télougou" },
  { code: "tg", name: "Tadjik" },
  { code: "th", name: "Thaï" },
  { code: "tk", name: "Turkmène" },
  { code: "tl", name: "Tagalog" },
  { code: "tr", name: "Turc" },
  { code: "tt", name: "Tatar" },
  { code: "uk", name: "Ukrainien" },
  { code: "ur", name: "Ourdou" },
  { code: "uz", name: "Ouzbek" },
  { code: "vi", name: "Vietnamien" },
  { code: "yi", name: "Yiddish" },
  { code: "yo", name: "Yoruba" },
  { code: "yue", name: "Cantonais" },
  { code: "zh", name: "Chinois" }
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"] | "auto";
export type LanguageName = (typeof LANGUAGES)[number]["name"] | "Auto";

export function languageName(code: LanguageCode): LanguageName | string {
  return LANGUAGES.find((l) => l.code === code)?.name ?? code.toUpperCase();
}
